---
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: init-job
    annotations:
      thoth-station.ninja/template-version: 0.1.0
    labels:
      app: thoth
      component: init-job
  spec:
    successfulBuildsHistoryLimit: 1
    failedBuildsHistoryLimit: 2
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 512Mi
    output:
      to:
        kind: ImageStreamTag
        name: "init-job:latest"
    source:
      type: Git
      git:
        uri: 'https://github.com/thoth-station/init-job'
        ref: 'master'
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: s2i-thoth-ubi8-py36:latest
        env:
          - name: ENABLE_PIPENV
            value: '1'
          - name: UPGRADE_PIP_TO_LATEST
            value: ''
          - name: "THOTH_DRY_RUN"
            value: "1"
          - name: "THOTH_ADVISE"
            value: "1"
          - name: "THAMOS_VERBOSE"
            value: "1"
          - name: "THAMOS_DEBUG"
            value: "0"
          - name: "THAMOS_CONFIG_TEMPLATE"
            value: ".thoth.yaml"
          - name: "THAMOS_CONFIG_EXPAND_ENV"
            value: "1"
    triggers:
      - type: ImageChange
        imageChange: {}
      - type: Generic
        generic:
          secretReference:
            name: generic-webhook-secret
